name: PR Verify

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4


    - name: Super-linter
      uses: super-linter/super-linter@v8.5.0 # x-release-please-version
      env:
        # To report GitHub Actions status checks
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0

    - name: 'Build'
      run: dotnet build --configuration Release ./src/github-actions-demo-app.csproj

    - name: 'Test'
      run: dotnet test --configuration Release ./test/github-actions-demo-app.Tests.csproj