name: PR Verify

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
    # - name: 'Login via Azure CLI'
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

    - name: Setup DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0

    - name: 'Build'
      run: dotnet build --configuration Release ./src/github-actions-demo-app.csproj

    - name: 'Test'
      run: dotnet test --configuration Release ./test/github-actions-demo-app.Tests.csproj